### ISSUE TITLE
Any plan of syncing with latest changes in git.yoctoproject.org/psplash ?

### ISSUE THREAD

**Issue by CodingPapi** [tano-systems/psplash-tn#1]
Hi, Thanks for your hard working.
is there any plan to sync with git.yoctoproject.org/psplash with systemd support?

**Comment by namedun** [comment]
Hi, We have no such plans at the moment, as this project is used primarily in the TanoWrt operating system, where procd is used as the initialization system. However, if we have some free time, we will definitely do it. The changes to support systemd don't look too large and difficult to sync. 

Also, we would be happy to accept a PR with these changes.
